apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "nocodb-helm.labels" . | nindent 4 }}
  name: {{ include "nocodb-helm.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
